# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=155)),
            ],
        ),
    ]
